### ISSUE TITLE
[ttx] Cannot decompile Apple’s Helvetica.dfont

### ISSUE THREAD

**Issue by brawer** [behdad/fonttools#232] opened 2015-04-15 06:26 UTC
Since a few hours ago, ttx fails to process the 'name' table in Helvetica.dfont of MacOS X 19.9.5. Before, ttx would handle this font perfectly fine. This might be cased by the following commit:
https://github.com/behdad/fonttools/commit/8b0152f0a1ced963775e3b8d1b938a55c6c64b7d

$ ./Tools/ttx Helvetica.dfont
[...]
Dumping 'name' table...
Traceback (most recent call last):
  File "./Tools/ttx", line 6, in <module>
    ttx.main(sys.argv[1:])
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttx.py", line 310, in main
    process(jobs, options)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttx.py", line 295, in process
    action(input, output, options)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttx.py", line 206, in ttDump
    bitmapGlyphDataFormat=options.bitmapGlyphDataFormat)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttLib/__init__.py", line 283, in saveXML
    self._tableToXML(tableWriter, tag, progress, quiet)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttLib/__init__.py", line 323, in _tableToXML
    table.toXML(writer, self)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttLib/tables/_n_a_m_e.py", line 72, in toXML
    name.toXML(writer, ttFont)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/ttLib/tables/_n_a_m_e.py", line 168, in toXML
    writer.write(unistr)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/misc/xmlWriter.py", line 48, in write
    self._writeraw(escape(string), indent=indent)
  File "/Users/sascha/src/fonttools2/fonttools/Tools/fontTools/misc/xmlWriter.py", line 73, in _writeraw
    self.file.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 0: ordinal not in range(128)

**Comment by brawer** [comment] 2015-04-15 06:27
This is on Python 2.7.5.

**Comment by behdad** [comment] 2015-04-15 17:45
Sounds like dupe of issue #233 which I just fixed.

**Closed by behdad** 2015-04-15 17:46 UTC

**Comment by brawer** [comment] 2015-04-15 17:48
Indeed, it's fixed now. Thank you!
