### ISSUE TITLE
Merge two TTX/TTF files into one TTC file

### ISSUE THREAD

**Issue by MitchTalmadge** [behdad/fonttools#651] opened 2016-08-16 03:23 UTC
I don't understand quite how TTC files work, so this might not be possible. I figured I'd ask the experts regardless.

I was able to convert a TTC file into two TTX files by using the `-y 0/1` command argument. Now I'd like to merge them back into a TTC file. Is this possible?

**Comment by anthrotype** [comment] 2016-08-16 08:09
Sorry, this is not supported yet. For now you can use this script in the Adobe FDK tools:
https://github.com/adobe-type-tools/afdko/blob/master/FDK/Tools/SharedData/FDKScripts/otf2otc.py

Closing as duplicate of https://github.com/behdad/fonttools/issues/17

**Closed by anthrotype** 2016-08-16 08:09 UTC
