### ISSUE TITLE
Support merging into .ttc

### ISSUE THREAD

**Issue by practik** [behdad/fonttools#250] opened 2015-04-22 20:28 UTC
For example, I can type 

`ttx -t name -y 1 Example.ttc`

to dump the name table of font 1 from Example.ttc. But it doesn’t seem possible to merge that table back into the TTC. If I type

`ttx -m Example.ttc Example-EditedNameTable.ttx`

I get the message “Error: specify a font number between 0 and 3 (inclusive)” – so TTX does recognize the nature of the problem. But there isn’t any way to specify the font number in this situation – is there? I’ve only been working with TTX for a couple of days, so maybe I’m missing it....

Anyway, this would be useful when you just want to make a small change to a TTC and don’t want to (or can’t) recreate the entire thing from TTFs.

**Comment by anthrotype** [comment] 2015-04-22 20:37
There's a similar request and related discussion at https://github.com/behdad/fonttools/issues/17

Currently it is only possible to read single fonts from a collection. Writing of TTC or OTC is not yet supported.
For now you could try using the two scripts from Adobe called otf2otc.py and otc2otf.py.

**Comment by practik** [comment] 2015-04-22 21:32
Well, at least I wasn't overlooking something obvious :-)  I'll check out the Adobe scripts.  Thanks!

**Comment by anthrotype** [comment] 2016-08-16 08:09
Duplicate of #17

**Closed by anthrotype** 2016-08-16 08:09 UTC
