### ISSUE TITLE
Take too much memory to dump EBDT/EBLC tables

### ISSUE THREAD

**Issue by tagoh** [behdad/fonttools#317] opened 2015-07-07 06:17 UTC
trying to dump sazanami-gothic.ttf to .ttx, for the version 2.4, it only took 140MB to be done, for 2.5, it doesn't even finish dumping after taking 4GB under ulimit usage - without ulimit, ttx is eventually killed by OOM.

**Comment by anthrotype** [comment] 2015-07-07 11:55
You're right. Here is the report from [memory_profiler](https://pypi.python.org/pypi/memory_profiler) when decompiling EBLC table of sazanami-gothic.ttf on a OS X Yosemite mac running Python 2.7.10.

There's one particular look which took me more than 8 GB of RAM before completing:

```
$ python -m memory_profiler Lib/fontTools/ttx.py -t "EBDT" -t "EBLC" -z extfile /Users/cosimolupo/Desktop/sazanami-gothic.ttf
Dumping "/Users/cosimolupo/Desktop/sazanami-gothic.ttf" to "/Users/cosimolupo/Desktop/sazanami-gothic#3.ttx"...
Dumping 'EBDT' table...
Dumping 'EBLC' table...
Filename: /Users/cosimolupo/Documents/Github/fonttools/Lib/fontTools/ttLib/tables/E_B_L_C_.py

Line #    Mem usage    Increment   Line Contents
================================================
    70   20.516 MiB    0.000 MiB   	@profile
    71                             	def decompile(self, data, ttFont):
    72                             
    73                             		# Save the original data because offsets are from the start of the table.
    74   20.520 MiB    0.004 MiB   		origData = data
    75                             
    76   21.688 MiB    1.168 MiB   		dummy, data = sstruct.unpack2(eblcHeaderFormat, data, self)
    77                             
    78   21.688 MiB    0.000 MiB   		self.strikes = []
    79   22.895 MiB    1.207 MiB   		for curStrikeIndex in range(self.numSizes):
    80   22.891 MiB   -0.004 MiB   			curStrike = Strike()
    81   22.891 MiB    0.000 MiB   			self.strikes.append(curStrike)
    82   22.891 MiB    0.000 MiB   			curTable = curStrike.bitmapSizeTable
    83   22.891 MiB    0.000 MiB   			dummy, data = sstruct.unpack2(bitmapSizeTableFormatPart1, data, curTable)
    84   22.895 MiB    0.004 MiB   			for metric in ('hori', 'vert'):
    85   22.891 MiB   -0.004 MiB   				metricObj = SbitLineMetrics()
    86   22.891 MiB    0.000 MiB   				vars(curTable)[metric] = metricObj
    87   22.895 MiB    0.004 MiB   				dummy, data = sstruct.unpack2(sbitLineMetricsFormat, data, metricObj)
    88   22.895 MiB    0.000 MiB   			dummy, data = sstruct.unpack2(bitmapSizeTableFormatPart2, data, curTable)
    89                             
    90 8823.176 MiB 8800.281 MiB   		for curStrike in self.strikes:
    91 8823.176 MiB    0.000 MiB   			curTable = curStrike.bitmapSizeTable
    92 9489.855 MiB  666.680 MiB   			for subtableIndex in range(curTable.numberOfIndexSubTables):
    93 9489.855 MiB    0.000 MiB   				lowerBound = curTable.indexSubTableArrayOffset + subtableIndex * indexSubTableArraySize
    94 9489.855 MiB    0.000 MiB   				upperBound = lowerBound + indexSubTableArraySize
    95 9489.855 MiB    0.000 MiB   				data = origData[lowerBound:upperBound]
    96                             
    97 9489.855 MiB    0.000 MiB   				tup = struct.unpack(indexSubTableArrayFormat, data)
    98 9489.855 MiB    0.000 MiB   				(firstGlyphIndex, lastGlyphIndex, additionalOffsetToIndexSubtable) = tup
    99 9489.855 MiB    0.000 MiB   				offsetToIndexSubTable = curTable.indexSubTableArrayOffset + additionalOffsetToIndexSubtable
   100 9489.695 MiB   -0.160 MiB   				data = origData[offsetToIndexSubTable:]
   101                             
   102 9489.305 MiB   -0.391 MiB   				tup = struct.unpack(indexSubHeaderFormat, data[:indexSubHeaderSize])
   103 9489.281 MiB   -0.023 MiB   				(indexFormat, imageFormat, imageDataOffset) = tup
   104                             
   105 9488.973 MiB   -0.309 MiB   				indexFormatClass = self.getIndexFormatClass(indexFormat)
   106 9489.852 MiB    0.879 MiB   				indexSubTable = indexFormatClass(data[indexSubHeaderSize:], ttFont)
   107 9489.852 MiB    0.000 MiB   				indexSubTable.firstGlyphIndex = firstGlyphIndex
   108 9489.852 MiB    0.000 MiB   				indexSubTable.lastGlyphIndex = lastGlyphIndex
   109 9489.852 MiB    0.000 MiB   				indexSubTable.additionalOffsetToIndexSubtable = additionalOffsetToIndexSubtable
   110 9489.855 MiB    0.004 MiB   				indexSubTable.indexFormat = indexFormat
   111 9489.855 MiB    0.000 MiB   				indexSubTable.imageFormat = imageFormat
   112 9489.855 MiB    0.000 MiB   				indexSubTable.imageDataOffset = imageDataOffset
   113 9489.855 MiB    0.000 MiB   				curStrike.indexSubTables.append(indexSubTable)
```

**Comment by anthrotype** [comment] 2015-07-07 12:19
I think it might related to this commit 97dea0a5d02ba1655d27a06fe91540e3495b8ef9 which replaced `xrange` (only defined in Python2) with `range` . Only in Python 3 the latter only returns an iterator.

**Comment by anthrotype** [comment] 2015-07-07 12:33
what about defining something like this in `fontTools.misc.py23`:

```python
try:
	xrange
except NameError:
	pass
else:
	range = xrange
````

so that whenever `range` is used, the iterator-version `xrange` gets used?

**Comment by tagoh** [comment] 2015-07-14 05:59
the problem still persists even after applying the suggestion in fontTools/misc/py23.py, unless I'm missing something else.

**Comment by adrientetar** [comment] 2015-07-29 15:04
@anthrotype: sounds good. I’d use python3 instead but that’s just me.

**Comment by anthrotype** [comment] 2015-07-29 15:07
the problem is xrange doesn't fix the excessive memory usage reported by @tagoh..
@adrientetar do you mind submitting a PR for that?

**Comment by behdad** [comment] 2015-08-18 15:54
It's equally broken for me on 2.5.

My guess is that it's just how things are, we probably are exploding every bit of each bitmap into a Python object!  Some sort of array-based internal representation might help.

**Comment by tagoh** [comment] 2016-02-09 03:06
Any progress on this?

**Comment by behdad** [comment] 2016-02-09 03:08
I'll try to take a look this week.

**Comment by pnemade** [comment] 2016-02-28 04:05
We really need this fixed in Fedora 24. Can someone from the fonttools developers look into this issue?

**Closed** 2016-03-02 19:53 UTC
